version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  
jobs:
  sonarqube:
    working_directory: ~/build
    docker:
        
        - image: cimg/node:23.0.0
    resource_class: small

    steps:
      - run: find .
      - attach_workspace:
            at: ~/workspace
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run SonarQube Scan
          command: |
            npm install -g sonar-scanner
      - run: |
            
            echo "Sonar org value is : "$SONAR_ORG
            sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url-https://sonarcloud.io \
            -Dsonar.exclusions="/android/,/ios/" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonarqube
