version: 2.1

jobs:
  sonar_scan:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run SonarQube Scan
          command: |
            npm install -g sonar-scanner
            sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://your-sonarqube-instance \
              -Dsonar.login=$SONARQUBE_TOKEN

workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonar_scan
