version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "hello world"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y unzip wget
      - run: |
          # Download the SonarQube scanner
          wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
          if [ $? -ne 0 ]; then
            echo "Failed to download sonar-scanner"
            exit 1
          fi
          
          # Unzip the downloaded file
          unzip -q sonar-scanner-cli-6.2.1.4610-linux-x64.zip
          if [ $? -ne 0 ]; then
            echo "Failed to unzip sonar-scanner"
            exit 1
          fi
          
          # Set the correct path
          export PATH=$PATH:$(pwd)/sonar-scanner-6.2.1.4610-linux-x64/bin
          echo "Sonar-scanner added to PATH"

      - run: |
          echo "Current working directory: $(pwd)"
          echo "Current PATH: $PATH"
          echo "Contents of the current directory:"
          ls -la
          echo "Contents of sonar-scanner directory:"
          ls -la sonar-scanner-6.2.1.4610-linux-x64/bin || echo "Directory not found"
          
          # Check for the sonar-scanner executable
          echo "Checking for sonar-scanner executable..."
          ls -la sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner || echo "sonar-scanner not found"
          
          # Check if sonar-scanner is executable
          if [ -x sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner ]; then
              echo "sonar-scanner is executable"
          else
              echo "sonar-scanner is NOT executable"
              exit 1
          fi

      - run: |
          echo "Checking if sonar-scanner is available in PATH..."
          if command -v sonar-scanner &> /dev/null; then
              echo "sonar-scanner command is available"
          else
              echo "sonar-scanner command is NOT available"
              exit 1
          fi

      - run: find .

      - attach_workspace:
          at: ~/workspace

      - run: |
          if [ -z "$CIRCLE_BRANCH" ]; then
            SONAR_BRANCH="main"
          else
            SONAR_BRANCH="$CIRCLE_BRANCH"
          fi
          echo "Sonar branch value is: $SONAR_BRANCH"
          echo "Sonar org value is : $SONAR_ORG"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.exclusions="/android/,/ios/" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
